


import type { Metadata } from "next";

import "./globals.css";

import Navbar from "@/components/shared/Navbar/Navbar";
import { Toaster } from "@/components/ui/sonner";







export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 

  return (
    <html lang="en">
      

      <body>
          
             
                <Navbar />
                <Toaster richColors position="top-center" />
                {children}
              
      </body>
    </html>
  );
}
